version: '3.7'
services:
  arangodb_db_container:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: password
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3

volumes:
  arangodb_data_container:
